import json
from collections import namedtuple


def load_policy(path):
    """Load policy from a json file that was generated by MedusaPolicyMining
program. Check for duplicate entries."""
    with open(path) as f:
        j = json.load(f)

        # Create a namedtuple according to the first entry from loaded json
        AccessRecord = namedtuple('AccessRecord', j[0].keys())

        records = {AccessRecord(**x) for x in j}

        return records
